### ISSUE TITLE
Support passing non-string data to signMessage

### ISSUE THREAD

**Issue by sprusr** [JoinColony/purser#192]
Currently the `signMessage` wallet method supports only a `message` parameter, which must be a UTF-8 string. However, in some circumstances we want to sign raw data such as a composed multisig transaction, which is in the format of a hex string or `UInt8Array`.

A possible solution which does not break the existing API is the addition of a `messageData` param:

```js
wallet.signMessage({ messageData: '0x123abc...' })
// or
wallet.signMessage({ messageData: new UInt8Array(...) })
```

Alternatively just detect if `UInt8Array` or hex string passed as `message`.

**Comment by rdig** [comment]
Note that this will need an accompanying [docs.colony.io](https://docs.colony.io/purser/docs-overview/) entry in order to:
- explain the reasoning for adding this param in
- show examples on how to use this

**Comment by rdig** [comment]
Please add an estimate to this after you're done :+1:
