### ISSUE TITLE
Unable to open wallet with mnemonic

### ISSUE THREAD

**Issue by pyskell** [JoinColony/purser#230]
The below fails.
```
import { open } from '@colony/purser-software';
var wallet = await open({"sting arrive festival trick chapter reward animal whip client alley twice lottery"})
```

Expected behavior is to get a wallet where the first account at the default derivation path is: `0x9d42A32ba574D25d2bd6cc002a5d54a424Cdb55d`

Instead it errors with:
```
Uncaught (in promise) Error: Could not open the wallet with the method you provided. Please check the arguments you passed in: password (undefined), privateKey (undefined), mnemonic ({mnemonic:0xa13b922e5a1c2757f6efa1d9b97752ef620bc6cdef5e43d44a466ceacfe98c17}), keystore (undefined), Error: cannot convert null value to array (arg="value", value=undefined, version=4.0.27)
    at _callee$ (index.js:153)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:271)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21
    at open (index.js:169)
```

FYI: This is a common mnemonic that ganache ships with by default, not exposing any important private keys here so no need to remove it.

**Comment by ryanchristo** [comment]
Hi @pyskell. It looks like you are missing the `mnemonic` object key. For example,

```
  // Get a wallet instance
  const wallet = await open({
    mnemonic: 'sting...',
  });
```

**Comment by ryanchristo** [comment]
I'm going to close this issue but feel free to reopen if you encounter a related issue.

**Comment by pyskell** [comment]
Problem persists with that as well. It seems like my bundler or something else in the build chain is mangling the object passed to purser (same for ethers.js) and turning it from a String -> Object.

Very peculiar but not an issue with your library (which is very cool btw).
