### ISSUE TITLE
Unable to log in with MetaMask wallet

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/purser#328]
*originally reported in the colonyDap repo:* https://github.com/JoinColony/colonyDapp/issues/2226

## Steps to reproduce

1. Make sure you're on the latest version of the Metamask extension (should update automatically)
2. Try to log in to the colony dapp.

## Expected behaviour

You should be able to log in

## Actual behaviour

Can't log in.
![image](https://user-images.githubusercontent.com/8453294/87493551-0182fe00-c61b-11ea-8728-e7af9f3aeb67.png)

## Suggestions (optional)

A new version of MetaMask was released, maybe there are some breaking changes

## side note
The template bug was almost spot on :joy:

**Comment by rdig** [comment]
This was patched by just doing a new RC release for the moment so that MetaMask continues to function.

The proper fix for this will come when we merge #322 and do new npm package releases.
